### PR TITLE
Example for basic multi-layer preceptron added

### PR DESCRIPTION
**Pull request by sbmalik**
This might be a helpful guide for the beginners. I properly documented each and every step for creating a basic MLP in pytorch and generating the wts file from it. I kept your coding style of building two files. I am preparing it's TensorRT counter part soon. 

@wang-xinyu I hope you found this useful and helpful for starters.

### CODE REVIEW

**Comment by wang-xinyu** [comment]
@sbmalik Thanks!
Do you think it's necessary since we already have a simple lenet?

**Comment by sbmalik** [comment]
@wang-xinyu It's actually for the TensorRT implementation of MLP in Python and C++, which I am working on. LeNet has some extra things too e.g. multiple layers and activations. 
Furthermore I think it is properly documented as well as it's **TensorRT** implementations are also going to be well documented. It might be helpful for the starters in cPP TensorRT APIs.

**Comment by wang-xinyu** [comment]
@sbmalik what do you mean by well documented? where is the doc?

**Comment by sbmalik** [comment]
@wang-xinyu I think I wrote all the **doc strings** properly. I will also wrote for TensorRTX counterparts.

**Comment by wang-xinyu** [comment]
@sbmalik OK, thanks

**Pull request merged**
